# Generated by Django 5.1.5 on 2025-02-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee Number')),
                ('birth_date', models.DateField(verbose_name='Birthday')),
                ('first_name', models.CharField(max_length=14, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=16, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
